language: python
sudo: false
matrix:
  include:
    - python: "3.3"
      env: PYZMQ="pyzmq"
    - python: "3.4"
      env: PYZMQ="pyzmq"
    - python: "3.5"
      env: PYZMQ="pyzmq"
    - python: "3.6"
      env: PYZMQ="pyzmq"
env:
  global:
    - secure: "fHTmXSkUyVFu7lJ4upcu4Xhv+5cTGq+SJ+GV9UUJ9guZYVWafxJw3CRmd/qqjucQzOTPg/2JA4/9XqDZDSWKKBwGTOgeiFjKaa4xPFO/bvpbECqR4y7TDh7k7zSjMCDD624b8k6LyWiaerh50ShU2CSi3cTjpyZWloolQWRotLM="
    - REPO: "ASPP/pelita"
# command to install dependencies
install:
  - pip install $PYZMQ --install-option="--zmq=bundled"
  - pip install pyyaml
  - pip install pytest-cov codecov coveralls
# command to run tests
script:
  - >
      python -c "import zmq; print('Using zmq %s.' % zmq.zmq_version())" &&
      python -c "import zmq; print('Using pyzmq %s.' % zmq.pyzmq_version())" &&
      PYTHONPATH=. py.test --cov=pelita -v test/ &&
      python -m pelita.scripts.pelita_main --progress &&
      python setup.py install &&
      for player in ./players/*Player.py ; do
          PYTHONPATH=.
          pelita --check-team $player || exit 1
          res=$(pelita --null --rounds 100 --filter small $player 2>&1)
          echo $res
          (echo $res | grep -q Exception) && exit 1
          echo "" # This resets the error code
      done

after_success:
  - codecov
  - coveralls
  - ./deploy-gh-pages.sh
